@baseURL = http://localhost:3333


// ------------- Admin Routes  ----------------- //
GET {{baseURL}}/helth

###
GET {{baseURL}}/users_admin
Authorization: Bearer {{token}}

###
GET {{baseURL}}/user_admin/12345678949
Authorization: Bearer {{token}}

### melhorar esta rota
GET {{baseURL}}/orders_admin 
Authorization: Bearer {{token}}

###
GET {{baseURL}}/products_admin
Authorization: Bearer {{token}}

###
GET {{baseURL}}/items_admin/abe388e5-571e-4fcb-977c-d6e662757ea6
Authorization: Bearer {{token}}

###
POST {{baseURL}}/order_admin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "CPF": "12345678949",
  "name": "Carlos Santos",
  "email": "carlos.santos@example.com",
  "endereco": "Rua das Palmeiras, 789",
  "data_nascimento": "1992-03-10",
  "telefone": "(31) 98765-4321",
  "valor_total": 50,
  "descricao": "O produto não liga mais",
  "items": [
    {
      "id_produto": "c208be64-1109-48c9-b5bc-10b28434c020",
      "quantidade": 1
    }
  ]
}

###
PATCH {{baseURL}}/order_admin/abe388e5-571e-4fcb-977c-d6e662757ea6/Pronto
Authorization: Bearer {{token}}

###
POST {{baseURL}}/product_admin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "TV Plsama 4p",
  "preco": 3999.90,
  "descricao": "Semi-nova-",
  "marca": "LG"
}

###
GET {{baseURL}}/product_admin/Tv
Authorization: Bearer {{token}}


###
# @name login
POST {{baseURL}}/login
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "CPF": "000.000.000-01",
  "senha": "senhafortedoAdministrador"  
}

###
@token = {{login.response.body.$.token}}

// ------------- Public Routes  ----------------- //
###
GET {{baseURL}}/user/12345678949

###
GET {{baseURL}}/order
Cookie: userId=e1eb7b56-9e64-4230-8b8f-f33ee415efcd

