@baseURL = http://localhost:3333


// ------------- Admin Routes  ----------------- //
GET {{baseURL}}/helth

###
GET {{baseURL}}/users_admin
Authorization: Bearer {{token}}

###
GET {{baseURL}}/user_admin/12345678949
Authorization: Bearer {{token}}

###
GET {{baseURL}}/orders_admin
Authorization: Bearer {{token}}

###
GET {{baseURL}}/products_admin
Authorization: Bearer {{token}}

###
GET {{baseURL}}/items_admin/48feef3a-a9e2-45ae-a107-4cf86b3b4002
Authorization: Bearer {{token}}

###
POST {{baseURL}}/order_admin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "CPF": "12345678949",
  "name": "Carlos Santos",
  "email": "carlos.santos@example.com",
  "endereco": "Rua das Palmeiras, 789",
  "data_nascimento": "1992-03-10",
  "telefone": "(31) 98765-4321",
  "items": [
    {
      "id_produto": "4245e747-04da-46b2-870e-ccafedb8b824",
      "quantidade": 1
    }
  ]
}

###
PATCH {{baseURL}}/order_admin/d48a6f91-1555-4c29-aa16-d21d136e0c08/Pronto
Authorization: Bearer {{token}}

###
POST {{baseURL}}/product_admin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "TV Plsama 4p",
  "preco": 3999.90,
  "descricao": "Semi-nova-",
  "marca": "LG"
}

###
GET {{baseURL}}/product_admin/Celular
Authorization: Bearer {{token}}


###
# @name login
POST {{baseURL}}/login
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "CPF": "000.000.000-01",
  "senha": "senhafortedoAdministrador"  
}

###
@token = {{login.response.body.$.token}}

// ------------- Public Routes  ----------------- //

###
GET {{baseURL}}/order
Cookie: userId=e1eb7b56-9e64-4230-8b8f-f33ee415efcd

###
GET {{baseURL}}/user/12345678949
